version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: content
      POSTGRES_PASSWORD: content
      POSTGRES_DB: content
    restart: always
    networks:
      - postgres
networks:
  postgres: